### ISSUE TITLE
Gatsby Build Error -  ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by awidjaja** [Airtable/airtable-gatsbyjs-blog#1]
![capture](https://user-images.githubusercontent.com/1708624/44036819-4fdae45e-9f45-11e8-8797-540a11e37f10.JPG)

**Comment by s2tephen** [comment]
I can't reproduce this on a fresh clone. Mind sharing details about your machine/dev environment, along with some repro steps?

**Comment by jbolda** [comment]
FYI, also got a report of the same error: https://github.com/jbolda/gatsby-source-airtable/issues/6

**Comment by s2tephen** [comment]
Cool, thanks for the heads up. Let us know if you find anything else out! Closing for now.
